### ISSUE TITLE
Buffer Overflow Error Crashes Client during Application Install

### ISSUE THREAD

**Issue by Mansalu** [slateci/slate-client-server#118]
@ike091 Discovered a crash in the SLATE client when attempting to perform an application install. His client version was compiled from commit 8ac1dad

```
slate app install --cluster utah-dev --group slate-dev --local /mnt/c/Isaak/SLATE/slate-open-ondemand/open-ondemand
*** buffer overflow detected ***: slate terminated
[1]    19709 abort (core dumped)  slate app install --cluster utah-dev --group slate-dev --local
```

The values file was

```
# Open OnDemand Configuration
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# The SLATE instance value.
Instance: "global"
replicaCount: 1
setupKeycloak: false
claimName: keycloak-db
SLATE:
  Cluster:
    DNSName: "utah-dev.slateci.net"
```
