### ISSUE TITLE
Expose allocatable/capacity resources per node in `slate cluster info` 

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-client-server#132]
I'd like to expose the "allocatable" and "capacity" fields in `slate cluster info` for each node in the cluster.

Here's a use case I ran into:

I wanted to deploy a Squid at a site, but I didn't know if there was enough free RAM to do so. 

From the API side, I confirmed that the RBAC has enough permissions to check the status of a node. From the YAML output I see the following fields:
```
    allocatable:
      cpu: "48"
      ephemeral-storage: "207720570127"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 196365672Ki
      pods: "110"
    capacity:
      cpu: "48"
      ephemeral-storage: 225391244Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 196468072Ki
      pods: "110"
```

I'm not sure they totally make sense - but maybe we could pull out some useful ones like CPUs and Memory (even if only the totals?) and expose them via `slate cluster info`.

Thoughts?
