### ISSUE TITLE
Ingress Subdomain Conflict

### ISSUE THREAD

**Issue by muali14** [slateci/slate-client-server#134]
When an ingress-enabled application is deployed with a subdomain that's already used in production by another K8s ingress, the slate cli informs the user that the application is successfully installed but the instance quietly fails due to the conflicting FQDNs of the corresponding two ingresses. As a result, the user can't access their instance via the ingress FQDN.

Can we alert the user when they choose an ingress subdomain that's not available so that they can change their selection and try to redeploy their application?

To test this, nginx can be deployed with two different config files that have different instance names and HTML `Data` content but same `Subdomain` value. For example, first config file can be:

```
Instance: test1

# The HTML data that nginx should serve
Data: |-
  <html>
  <body>
  <h1>Hello world!</h1>
  <h1>This is the first deployment!</h1>
  </body>
  </html>

# Ingress control settings  
Ingress:
  # If true, use ingress control.
  # Otherwise, generic NodePort networking will be used, 
  # and the other settings in this section will be ignored. 
  Enabled: true
  # The subdomain to associate with this service.
  # This will result in a FQDN like {subdomain}.{cluster}.slateci.net
  Subdomain: hello
  # The class of the ingress controller to use. 
  # For SLATE this should be 'slate'. 
  Class: slate

#Defines what IP ranges can access the app
#If disabled all IP addresses can access the app
NetworkPolicy:
  Enabled: false
  AllowedCIDRs: 
    - 0.0.0.0/0

``` 

and the second config file can be:

```
Instance: test2

# The HTML data that nginx should serve
Data: |-
  <html>
  <body>
  <h1>Hello world!</h1>
  <h1>This is the second deployment!</h1>
  </body>
  </html>

# Ingress control settings  
Ingress:
  # If true, use ingress control.
  # Otherwise, generic NodePort networking will be used, 
  # and the other settings in this section will be ignored. 
  Enabled: true
  # The subdomain to associate with this service.
  # This will result in a FQDN like {subdomain}.{cluster}.slateci.net
  Subdomain: hello
  # The class of the ingress controller to use. 
  # For SLATE this should be 'slate'. 
  Class: slate

#Defines what IP ranges can access the app
#If disabled all IP addresses can access the app
NetworkPolicy:
  Enabled: false
  AllowedCIDRs: 
    - 0.0.0.0/0

```
