### ISSUE TITLE
Investigate feasibility of mutating deployments to inject some SLATE metadata as environment variables

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-client-server#138]
It might be nice to inject some SLATE metadata.

e.g., 

```
SLATE_GROUP = atlas-squid
SLATE_GROUP_EMAIL = atlas-squid-foo@bar.baz
```

This would be for init containers, lifecycle hooks, etc to pick up some contextual information and do something with it. 

Either doing it at a Helm level or mutating the deployment directly. I.e. ,for Helm you could imagine having

```
spec:
  template:
    spec:
      containers:
      - name: osg-frontier-squid
        image: "opensciencegrid/frontier-squid:stable"
        env:
        {{ if .SLATE.Metadata.Group }}
        - name: SLATE_GROUP
          value: {{ .SLATE.Metadata.Group }}
        {{ end }}
        {{ if .SLATE.Metadata.GroupEmail }}
        - name: SLATE_GROUP_EMAIL
          value: {{ .SLATE.Metadata.GroupEmail }}
        {{ end }}
```

I think this would require that the SLATE API would need to inject the values at install time. 

Thoughts?
