### ISSUE TITLE
Bump pod RAM request to 2048Mi

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-client-server#355]
See title.
```yaml
resources:
      requests:
        memory: "2048Mi"
```
