### ISSUE TITLE
Set up signoz on gke

### ISSUE THREAD

**Issue by sthapa** [slateci/slate-client-server#385]
Set up Signoz on GKE so that we can use that and retire the dev instance on river.   The signoz chart is at https://charts.signoz.io 
and the values file is 

```yaml
global:
  storageClass: "rook-ceph-block"

frontend:
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
    hosts:
      - host: signoz.slateci.io
        paths:
          - path: /
            pathType: Prefix
            port: 3301

otelCollector:
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
    hosts:
      - host: otel-collector.slateci.io
        paths:
          - path: /
            pathType: Prefix
            port: 4318


k8s-infra:
  enabled: false
```
