### ISSUE TITLE
Decrease containers.name.resources.requests.memory to 3Gi

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-client-server#396]
Update the following in `./resources/chart/templates/deployment.yml` to reflect `3Gi`. Right now we cannot schedule more pods on the `primus-api` node pool despite all three nodes having `8Gi` of RAM.
```yaml
containers:
  - name: slate-api
    ...
    resources:
      requests:
        memory: "3Gi"
```
