### ISSUE TITLE
Chart: remove resource request and primus-api node pool

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-client-server#401]
In `./resources/chart/templates/deployment.yml`, remove the memory request displayed below:
```yaml
...
spec:
      containers:
        - name: slate-api
          image: "{{ .Values.harbor.hostname }}/{{ .Values.harbor.projectID }}/slate-api:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "3Gi"
          ports:
...
```
and change the `nodeSelector` back to `primus-other`:
```yaml
nodeSelector:
        cloud.google.com/gke-nodepool: primus-api
```
