### ISSUE TITLE
Increase GKE Load balancer timeout to 10 minutes

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-client-server#435]
In `./resources/chart/templates/gcp`:
```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
...
spec:
  ...
  timeoutSec: 600
```
