### ISSUE TITLE
Shell comments getting eaten on app install

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-client-server#62]
An example application such as osg-hosted-ce gets shell comments chomped. Here's an example:
```
CustomizationScript: |+
  #!/bin/sh
  echo "+AccountingGroup=osg"
```

In the chart we have, correspondingly:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: osg-hosted-ce-{{ .Values.Instance }}-cluster-configuration
  labels:
    app: osg-hosted-ce
    chart: {{ template "osg-hosted-ce.chart" . }}
    instance: {{ .Values.Instance }}
    release: {{ .Release.Name }}
data:
  {{ .Values.Cluster.Batch }}-local-submit-attributes.sh: |+
{{ .Values.CustomizationScript | indent 4 }}
```

After installing we see the following in `slate instance info`:
```
CustomizationScript: |+
  echo "+AccountingGroup=osg"
```

Indeed, in kubernetes we also see:
```
# kubectl get configmap -n slate-group-slate-dev osg-hosted-ce--cluster-configuration -o yaml
apiVersion: v1
data:
  condor-local-submit-attributes.sh: |
    echo "+AccountingGroup=osg"
kind: ConfigMap
```

This is less important for an HTCondor cluster, but it's critical for deployment on a SLURM cluster, where the shell quotes are part of the SLURM pre-processor thingy.
